package 예외처리;

public class 에러발생 {

	public static void main(String[] args) {
//		에러발생2 error = new 에러발생2();
//		error.call();
		에러발생3 error2 = new 에러발생3();
//		try {
//			error2.call();
//		} catch (Exception e) {
//			System.out.println("함수를 호출한 곳에서 예외처리함.");
//			System.out.println("관리자에게 문자를 보냄.");
//		}
	}

}
